### ISSUE TITLE
Does sandbox mode work the provided version of coinbase-pro-node?

### ISSUE THREAD

**Issue by JumboLove** [brendanjryan/coinbase-dca#2]
I wanted to run a bit of testing on this on my sandbox before turning it loose on my real account. It seems to be trying to auth against the main REST API instead of  the sandbox REST API.
![image](https://user-images.githubusercontent.com/1929202/111086792-758fe180-84db-11eb-970e-7a1cc0c10f4d.png)

The coinbase-pro-node made updates so the client is constructed with `useSandbox` as a separate parameter from the `auth` object.
https://github.com/bennycode/coinbase-pro-node/pull/20/files

I haven't dug into whether this is the issue or I've misconfigured something on my end.  Can you run a quick test and let me know?

**Comment by brendanjryan** [comment]
per #3 this should now work -- LMK if you run into any issues!
